import Navbar from "@/components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/authProvider";
import { LoadingPage } from "@/components/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "3D 프린터 현황",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`${inter.className} bg-[#fafafa]`}>
          <AuthProvider>
            <LoadingPage />
            <Navbar className="fixed top-0" />
            {children}
          </AuthProvider>
      </body>
    </html>
  );
}
